### ISSUE TITLE
Recommendation for using cookies with clj-http-lite

### ISSUE THREAD

**Issue by devurandom** [clj-commons/clj-http-lite#71]
The readme states that clj-http-lite does not support cookies directly. Do you have a recommendation for how to implement (standard conforming) cookie handling when using clj-http-lite? Which additional libraries might be helpful?

**Comment by lread** [comment]
Hi @devurandom, clj-http-lite is a light library. I'm guessing that's why it opted to not support cookies. Your usage could look at request and response headers to do your own cookie support, but you'd have to decide if that's more awkward than it is worth for your use case.

Perhaps switching to a heavier-weight library would be a better bet?
If you are working from the JVM, [clj-http](https://github.com/dakrone/clj-http) (jdk8+) or [hato](https://github.com/gnarroway/hato) (jdk11+) might be worth a look.

If you are working from babashka you could explore [babashka/http-client](https://github.com/babashka/http-client) (jdk11+ when used from JVM). I don't see cookie support documented for it. So you might need to dig/ask a bit if exploring it as an option.

**Comment by borkdude** [comment]
babashka.http-client has supported for `:cookie-handler` but currently you have to construct it manually like it's done in hato here:

https://github.com/gnarroway/hato/blob/7862f9e3ab692ea499b935842978688831e61bfd/src/hato/client.clj#L167-L205

This code works in babashka. I'm open to making it easier to construct such a cookie-handler via idiomatic clojure though :)

**Comment by devurandom** [comment]
Thanks for both your replies!

I also found https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.Builder.html#cookieHandler(java.net.CookieHandler) and https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/CookieManager.html#%3Cinit%3E(java.net.CookieStore,java.net.CookiePolicy) after Lee's reply and will see whether to create a commonly useful wrapper or just use it directly.

I will close this issue until then, assuming that this provides enough hints for others who also want to use cookies with the more lightweight HTTP libraries.
